In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/workspaces/tir103/data-pipeline/resource/holding.csv", nrows=1000000)

In [4]:
len(df)

1000000

In [5]:
df

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
999995,3092652,2020/12/31,23,2021/01/08,0.50,8556.0,6.633467e+05,CLOUDFLARE INC,18915M10
999996,3092652,2020/12/31,24,2021/01/08,0.50,2208.0,6.610973e+05,AUTODESK INC,05276910
999997,3092652,2020/12/31,25,2021/01/08,0.50,13662.0,6.609676e+05,WORLD WRESTLING ENTMT INC,98156Q10
999998,3092652,2020/12/31,26,2021/01/08,0.50,1794.0,6.589003e+05,POOL CORP,73278L10
999999,3092652,2020/12/31,27,2021/01/08,0.50,10902.0,6.554282e+05,INTERACTIVE BROKERS GROUP INC,45841N10

In [6]:
df.head()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10

In [7]:
df.head(20)

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
6,2998623,2020/11/30,7,2021/01/08,1.63,2194727.0,1.976352e+08,C S X CORP,12640810
7,2998623,2020/11/30,8,2021/01/08,1.60,5045923.0,1.939653e+08,AMERICAN INTERNATIONAL GROUP INC,02687478
8,2998623,2020/11/30,9,2021/01/08,1.59,1403360.0,1.937619e+08,P N C FINANCIAL SERVICES GRP INC,69347510
9,2998623,2020/11/30,10,2021/01/08,1.54,3065766.0,1.874409e+08,C B R E GROUP INC,12504L10
10,2998623,2020/11/30,11,2021/01/08,1.54,186854700.0,1.869642e+08,US Treasury 0.375% 30-Nov-2025,91282CAZ
11,2998623,2020/11/30,12,2021/01/08,1.52,6737689.0,1.842758e+08,WELLS FARGO & CO NEW,94974610
12,2998623,2020/11/30,13,2021/01/08,1.50,3968733.0,1.827205e+08,JOHNSON CONTROLS INTL PLC,G5150210
13,2998623,2020/11/30,14,2021/01/08,1.50,182211000.0,1.821434e+08,United States of America (Government) .125% 30...,91282CAX
14,2998623,2020/11/30,15,2021/01/08,1.50,583989.0,1.819243e+08,ANTHEM INC,03675210
15,2998623,2020/11/30,16,2021/01/08,1.46,1208147.0,1.778030e+08,QUALCOMM INC,74752510
16,2998623,2020/11/30,17,2021/01/08,1.43,1161825.0,1.735186e+08,GENERAL DYNAMICS CORP,36955010
17,2998623,2020/11/30,18,2021/01/08,1.39,5156744.0,1.684193e+08,CITIZENS FINANCIAL GROUP INC,17461010
18,2998623,2020/11/30,19,2021/01/08,1.36,165210387.0,1.652104e+08,Invesco Treasury Portfolio;Institutional,82525240
19,2998623,2020/11/30,20,2021/01/08,1.31,3420381.0,1.587741e+08,TRUIST FINANCIAL CORP,89832Q10

In [8]:
df.tail()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
999995,3092652,2020/12/31,23,2021/01/08,0.5,8556.0,663346.68,CLOUDFLARE INC,18915M10
999996,3092652,2020/12/31,24,2021/01/08,0.5,2208.0,661097.28,AUTODESK INC,05276910
999997,3092652,2020/12/31,25,2021/01/08,0.5,13662.0,660967.56,WORLD WRESTLING ENTMT INC,98156Q10
999998,3092652,2020/12/31,26,2021/01/08,0.5,1794.0,658900.32,POOL CORP,73278L10
999999,3092652,2020/12/31,27,2021/01/08,0.5,10902.0,655428.24,INTERACTIVE BROKERS GROUP INC,45841N10

In [9]:
df.head(20).tail()

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
15,2998623,2020/11/30,16,2021/01/08,1.46,1208147.0,1.778030e+08,QUALCOMM INC,74752510
16,2998623,2020/11/30,17,2021/01/08,1.43,1161825.0,1.735186e+08,GENERAL DYNAMICS CORP,36955010
17,2998623,2020/11/30,18,2021/01/08,1.39,5156744.0,1.684193e+08,CITIZENS FINANCIAL GROUP INC,17461010
18,2998623,2020/11/30,19,2021/01/08,1.36,165210387.0,1.652104e+08,Invesco Treasury Portfolio;Institutional,82525240
19,2998623,2020/11/30,20,2021/01/08,1.31,3420381.0,1.587741e+08,TRUIST FINANCIAL CORP,89832Q10

In [10]:
df[500:505]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
500,2998821,2020/11/30,3,2021/01/08,2.74,585810.0,47204569.80,ENCOMPASS HEALTH CORP,29261A10
501,2998821,2020/11/30,4,2021/01/08,2.73,1019787.0,46950993.48,JOHNSON CONTROLS INTL PLC,G5150210
502,2998821,2020/11/30,5,2021/01/08,2.71,1645462.0,46599483.84,TAPESTRY INC,87603010
503,2998821,2020/11/30,6,2021/01/08,2.60,883918.0,44726250.80,KIRBY CORP,49726610
504,2998821,2020/11/30,7,2021/01/08,2.57,988193.0,44271046.40,CIENA CORP,17177930

In [11]:
df.loc[[1,3,5,7],"portno":"eff_dt"]

    portno   report_dt  security_rank      eff_dt
1  2998623  2020/11/30              2  2021/01/08
3  2998623  2020/11/30              4  2021/01/08
5  2998623  2020/11/30              6  2021/01/08
7  2998623  2020/11/30              8  2021/01/08

In [12]:
df.loc[[1,3,5,7], ["portno", "eff_dt", "security_rank"]]

    portno      eff_dt  security_rank
1  2998623  2021/01/08              2
3  2998623  2021/01/08              4
5  2998623  2021/01/08              6
7  2998623  2021/01/08              8

In [13]:
df.iloc[[1,3,5,7], [0, 5, 7]]

    portno  nbr_shares                     security_name
1  2998623   3087680.0    COGNIZANT TECHNOLOGY SOLS CORP
3  2998623   2815186.0   PHILIP MORRIS INTERNATIONAL INC
5  2998623    866386.0           GOLDMAN SACHS GROUP INC
7  2998623   5045923.0  AMERICAN INTERNATIONAL GROUP INC

In [14]:
df.columns

Index(['portno', 'report_dt', 'security_rank', 'eff_dt', 'percent_tna',
       'nbr_shares', 'market_val', 'security_name', 'cusip'],
      dtype='object')

In [15]:
df.dtypes

portno            object
report_dt         object
security_rank      int64
eff_dt            object
percent_tna      float64
nbr_shares       float64
market_val       float64
security_name     object
cusip             object
dtype: object

In [16]:
df["cusip"].dtype

dtype('O')

In [17]:
df["security_rank"].dtype

dtype('int64')

In [18]:
df["portno"].unique()

array(['2998623', '2998638', '2998809', ..., '3092616', '3092619',
       '3092652'], dtype=object)

In [19]:
len(df)

1000000

In [20]:
len(df["portno"].unique())

3867

In [21]:
df["market_val"].mean()

np.float64(8295992.487287326)

In [22]:
df["market_val"].std()

np.float64(81533843.61393921)

In [23]:
df["market_val"].max()

np.float64(18628182175.98)

In [24]:
df["market_val"].min()

np.float64(-7381044552.0)

In [25]:
df.describe()

        security_rank     percent_tna    nbr_shares    market_val
count  1000000.000000  1000000.000000  1.000000e+06  1.000000e+06
mean       878.182552        0.313768  4.992272e+07  8.295992e+06
std       1319.490208        1.713193  1.176281e+10  8.153384e+07
min          1.000000     -200.000000 -4.398750e+12 -7.381045e+09
25%        116.000000        0.010000  2.069500e+04  1.783209e+05
50%        398.000000        0.050000  2.000000e+05  8.666431e+05
75%       1090.000000        0.210000  1.208042e+06  3.516512e+06
max      12388.000000      300.080000  6.667220e+12  1.862818e+10

In [26]:
df["portno"].value_counts()

portno
3076812    10798
3062442     9285
3092256     8456
307883d     8331
3062436     7676
           ...
3075153        1
307512c        1
3073329        1
3080052        1
3082554        1
Name: count, Length: 3867, dtype: int64

In [28]:
df["portno"] == "2998623"

0          True
1          True
2          True
3          True
4          True
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Name: portno, Length: 1000000, dtype: bool

In [29]:
df[df["portno"] == "2998623"]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
346,2998623,2020/11/30,352,2021/01/08,0.00,1303.0,1.594570e+03,Ginnie Mae 2 20-JAN-2031 003028,36202DLH
347,2998623,2020/11/30,352,2021/01/08,0.00,3702.0,3.726940e+03,Gvt Ntl Mrtg Asn 15-Jun-2026 422949,36206VZN
348,2998623,2020/11/30,352,2021/01/08,0.00,5645.0,5.665600e+03,Fannie Mae 01-Jul-2032 642656,31390C5R
349,2998623,2020/11/30,352,2021/01/08,0.00,1.0,1.070000e+00,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG
350,2998623,2020/11/30,352,2021/01/08,0.00,0.0,6.370000e+00,VIATRIS INC,92556V10

In [30]:
df[
    df["portno"].isin(["3092616", "2998623"])
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
...,...,...,...,...,...,...,...,...,...
347,2998623,2020/11/30,352,2021/01/08,0.00,3702.0,3.726940e+03,Gvt Ntl Mrtg Asn 15-Jun-2026 422949,36206VZN
348,2998623,2020/11/30,352,2021/01/08,0.00,5645.0,5.665600e+03,Fannie Mae 01-Jul-2032 642656,31390C5R
349,2998623,2020/11/30,352,2021/01/08,0.00,1.0,1.070000e+00,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG
350,2998623,2020/11/30,352,2021/01/08,0.00,0.0,6.370000e+00,VIATRIS INC,92556V10
999569,3092616,2020/09/30,259,2021/01/08,0.07,31986.0,6.994347e+05,SABIC Agri-Nutrients Co ORD,M8T36M10

In [34]:
portno_filter = df["portno"].isin(["3092616", "2998623"])
percent_gt_2_filter = df["percent_tna"] > 2

In [35]:
df[
    portno_filter & percent_gt_2_filter
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10

In [33]:
percent_lt_1_filter = df["percent_tna"] < 1

In [36]:
df[
    percent_gt_2_filter | percent_lt_1_filter
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
32,2998623,2020/11/30,33,2021/01/08,0.97,2350480.0,1.180881e+08,COMCAST CORP NEW,20030N10
33,2998623,2020/11/30,34,2021/01/08,0.94,724928.0,1.148431e+08,N X P SEMICONDUCTORS N V,N6596X10
34,2998623,2020/11/30,35,2021/01/08,0.94,3616628.0,1.138514e+08,US FOODS HOLDING CORP,91200810
35,2998623,2020/11/30,36,2021/01/08,0.91,2015089.0,1.109710e+08,CITIGROUP INC,17296742
...,...,...,...,...,...,...,...,...,...
999995,3092652,2020/12/31,23,2021/01/08,0.50,8556.0,6.633467e+05,CLOUDFLARE INC,18915M10
999996,3092652,2020/12/31,24,2021/01/08,0.50,2208.0,6.610973e+05,AUTODESK INC,05276910
999997,3092652,2020/12/31,25,2021/01/08,0.50,13662.0,6.609676e+05,WORLD WRESTLING ENTMT INC,98156Q10
999998,3092652,2020/12/31,26,2021/01/08,0.50,1794.0,6.589003e+05,POOL CORP,73278L10
999999,3092652,2020/12/31,27,2021/01/08,0.50,10902.0,6.554282e+05,INTERACTIVE BROKERS GROUP INC,45841N10

In [37]:
df[
    portno_filter & (percent_gt_2_filter | percent_lt_1_filter)
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
0,2998623,2020/11/30,1,2021/01/08,2.55,7078982.0,3.103426e+08,GENERAL MOTORS CO,37045V10
32,2998623,2020/11/30,33,2021/01/08,0.97,2350480.0,1.180881e+08,COMCAST CORP NEW,20030N10
33,2998623,2020/11/30,34,2021/01/08,0.94,724928.0,1.148431e+08,N X P SEMICONDUCTORS N V,N6596X10
34,2998623,2020/11/30,35,2021/01/08,0.94,3616628.0,1.138514e+08,US FOODS HOLDING CORP,91200810
35,2998623,2020/11/30,36,2021/01/08,0.91,2015089.0,1.109710e+08,CITIGROUP INC,17296742
...,...,...,...,...,...,...,...,...,...
347,2998623,2020/11/30,352,2021/01/08,0.00,3702.0,3.726940e+03,Gvt Ntl Mrtg Asn 15-Jun-2026 422949,36206VZN
348,2998623,2020/11/30,352,2021/01/08,0.00,5645.0,5.665600e+03,Fannie Mae 01-Jul-2032 642656,31390C5R
349,2998623,2020/11/30,352,2021/01/08,0.00,1.0,1.070000e+00,Fannie Mae 01-MAR-2021 866003 Pd Down,31409BDG
350,2998623,2020/11/30,352,2021/01/08,0.00,0.0,6.370000e+00,VIATRIS INC,92556V10
999569,3092616,2020/09/30,259,2021/01/08,0.07,31986.0,6.994347e+05,SABIC Agri-Nutrients Co ORD,M8T36M10

In [38]:
df[
    ~(portno_filter & (percent_gt_2_filter | percent_lt_1_filter))
]

,portno,report_dt,security_rank,eff_dt,percent_tna,nbr_shares,market_val,security_name,cusip
1,2998623,2020/11/30,2,2021/01/08,1.98,3087680.0,2.412404e+08,COGNIZANT TECHNOLOGY SOLS CORP,19244610
2,2998623,2020/11/30,3,2021/01/08,1.89,3714760.0,2.296836e+08,MORGAN STANLEY DEAN WITTER & CO,61744644
3,2998623,2020/11/30,4,2021/01/08,1.75,2815186.0,2.132503e+08,PHILIP MORRIS INTERNATIONAL INC,71817210
4,2998623,2020/11/30,5,2021/01/08,1.65,5248941.0,2.011394e+08,CORTEVA INC,22052L10
5,2998623,2020/11/30,6,2021/01/08,1.64,866386.0,1.997713e+08,GOLDMAN SACHS GROUP INC,38141G10
...,...,...,...,...,...,...,...,...,...
999995,3092652,2020/12/31,23,2021/01/08,0.50,8556.0,6.633467e+05,CLOUDFLARE INC,18915M10
999996,3092652,2020/12/31,24,2021/01/08,0.50,2208.0,6.610973e+05,AUTODESK INC,05276910
999997,3092652,2020/12/31,25,2021/01/08,0.50,13662.0,6.609676e+05,WORLD WRESTLING ENTMT INC,98156Q10
999998,3092652,2020/12/31,26,2021/01/08,0.50,1794.0,6.589003e+05,POOL CORP,73278L10
999999,3092652,2020/12/31,27,2021/01/08,0.50,10902.0,6.554282e+05,INTERACTIVE BROKERS GROUP INC,45841N10

In [39]:
df.groupby("portno")

In [40]:
df.groupby("portno").size()

portno
2998623    351
2998638     77
2998809     70
2998821     54
2999052      2
          ...
309260a      2
309260d    514
3092616      1
3092619    403
3092652     27
Length: 3867, dtype: int64

In [42]:
df.groupby("portno").sum()["market_val"]

portno
2998623    1.213476e+10
2998638    8.460393e+09
2998809    1.989293e+09
2998821    1.721541e+09
2999052    8.558093e+05
               ...
309260a    1.133305e+06
309260d    1.738378e+08
3092616    6.994347e+05
3092619    5.070766e+06
3092652    1.563519e+08
Name: market_val, Length: 3867, dtype: float64

In [43]:
df.groupby("portno").sum(numeric_only=True)

         security_rank  percent_tna    nbr_shares    market_val
portno
2998623          61888        99.79  3.817768e+09  1.213476e+10
2998638           3021        99.89  4.856478e+08  8.460393e+09
2998809           2485        99.50  1.312320e+08  1.989293e+09
2998821           1485       100.01  7.659816e+07  1.721541e+09
2999052            634         0.08  8.600000e+05  8.558093e+05
...                ...          ...           ...           ...
309260a            439         0.10  5.265000e+06  1.133305e+06
309260d         133030       100.79 -1.411982e+10  1.738378e+08
3092616            259         0.07  3.198600e+04  6.994347e+05
3092619          81372       100.06  5.315248e+06  5.070766e+06
3092652            377       118.57  1.346848e+08  1.563519e+08

[3867 rows x 4 columns]

In [44]:
df.groupby(["portno", "eff_dt"])["percent_tna"].sum

portno   eff_dt
2998623  2021/01/08     99.79
2998638  2021/01/08     99.89
2998809  2021/01/08     99.50
2998821  2021/01/08    100.01
2999052  2021/01/08      0.08
                        ...
309260a  2021/01/08      0.10
309260d  2021/01/08    100.79
3092616  2021/01/08      0.07
3092619  2021/01/08    100.06
3092652  2021/01/08    118.57
Name: percent_tna, Length: 3867, dtype: float64